events {
    worker_connections 1024;
}

http {
  upstream app1_upstream { server app1:8080; }   # app1 연결 대상
  upstream app2_upstream { server app2:8080; }   # app2 연결 대상

  server {
    listen 80;                                   # 80 포트 수신

    location /app1 { proxy_pass http://app1_upstream/; }
    location /app2 { proxy_pass http://app2_upstream/; }

    location = / { return 302 /app1; }    
    
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;      # 기본 진입 경로는 app1으로
  }
}