# --------------------------------------
# [기본 애플리케이션 설정]
# --------------------------------------
spring.application.name=spring-base64
server.port=8080

# --------------------------------------
# [H2 Database 설정]
# --------------------------------------
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA 설정 (Entity 기반 테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ----------------------------------------
# 정적 리소스 (이미지 파일 접근용)
# => /uploads/ 경로를 로컬 폴더로 매핑
# ----------------------------------------
spring.web.resources.static-locations=file:uploads/

