#!/usr/bin/env python3
"""auto_fit.py — HTML PDF 자동 페이지 밀도 조정

pub-html-build + pub-html-to-pdf로 PDF 빌드 → pub-layout-check로 이슈 감지
→ CSS density-scale 점진 축소 → 이슈 없어질 때까지 반복.

사용법:
    python auto_fit.py --project-root projects/사내AI비서_v2 --chapter 1
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


# ── 스킬·도구 경로 ────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parents[3]
BUILD_HTML = REPO_ROOT / ".claude/skills/pub-html-build/build_html.py"
BUILD_PDF = REPO_ROOT / ".claude/skills/pub-html-to-pdf/build_pdf.py"
_MAC_VENV = REPO_ROOT / ".claude/skills/pub-html-to-pdf/.venv/bin/python"
PDF_VENV_PY = _MAC_VENV if _MAC_VENV.exists() else Path(sys.executable)
LAYOUT_CHECKER = REPO_ROOT / ".claude/skills/pub-layout-check/references/scripts/pdf_layout_checker.py"


# ── density scale → CSS 생성 ──────────────────────────────────
def density_css(scale: float) -> str:
    """density scale (0.75~1.0)에 따라 주요 컴포넌트 padding·gap·margin을 재정의.
    base = 스킬 기본값 (diagrams.css). scaled = round(base * scale).
    """
    def px(base: int) -> str:
        return f"{round(base * scale)}px"

    return f"""/* Auto-generated by pub-page-fit-html (density={scale:.2f}) */
.figure-group {{
  padding: {px(22)} !important;
  gap: {px(18)} !important;
}}
.rag-pipeline-box {{ padding: {px(24)} !important; }}
.rag-step {{ padding: {px(18)} !important; }}
.rag-step .s-meta {{
  margin-bottom: {px(14)} !important;
  padding-bottom: {px(10)} !important;
}}
.llm-rag-split {{
  padding: {px(22)} {px(20)} !important;
  gap: {px(16)} !important;
}}
.lrs-paths {{ gap: {px(12)} !important; }}
.lrs-path {{ gap: {px(12)} !important; }}
.librarian-scene {{ padding: {px(28)} {px(24)} !important; }}
.terminal-log .tl-body {{ padding: {px(16)} {px(20)} !important; }}
.annotated-compare {{ margin: {px(24)} 0 !important; }}
.ac-block {{
  padding: {px(16)} {px(20)} !important;
  margin-bottom: {px(12)} !important;
}}
"""


# ── pub-layout-check 출력 파싱 ────────────────────────────────
PAGE_LINE = re.compile(r"^\s*p(\d+)\s*\|[#.]+\|\s*(\d+)%")


def run_layout_check(pdf_path: Path, min_usage: int) -> tuple[int, list[tuple[int, int]]]:
    """PDF 레이아웃 분석 → (전체 페이지 수, 문제 페이지 [(page, usage%)]).
    표지/목차 제외, 마지막 페이지 제외 (끝맺음 자연 공백)."""
    result = subprocess.run(
        [str(PDF_VENV_PY), str(LAYOUT_CHECKER), str(pdf_path)],
        capture_output=True, text=True, timeout=60,
    )
    out = result.stdout
    pages: list[tuple[int, int]] = []
    for line in out.splitlines():
        m = PAGE_LINE.match(line)
        if m:
            pages.append((int(m.group(1)), int(m.group(2))))
    if not pages:
        return 0, []
    last_page = max(p for p, _ in pages)
    issues = [(p, u) for p, u in pages if u < min_usage and p < last_page]
    return len(pages), issues


# ── 빌드 실행 ─────────────────────────────────────────────────
def rebuild(project_root: Path, chapter: int) -> Path:
    """HTML + PDF 재빌드. 생성된 PDF 경로 반환."""
    subprocess.run(
        [str(PDF_VENV_PY), str(BUILD_HTML), "--project-root", str(project_root), "--chapter", str(chapter)],
        check=True, cwd=REPO_ROOT,
    )
    subprocess.run(
        [str(PDF_VENV_PY), str(BUILD_PDF),
         "--project-root", str(project_root), "--chapter", str(chapter), "--no-pagedjs"],
        check=True, cwd=REPO_ROOT,
    )
    pdf_dir = project_root / ".build/pdf"
    candidates = sorted(pdf_dir.glob(f"{chapter:02d}-*.pdf"))
    if not candidates:
        raise RuntimeError(f"PDF not found in {pdf_dir}")
    return candidates[0]


# ── 메인 루프 ─────────────────────────────────────────────────
def main() -> int:
    parser = argparse.ArgumentParser(description="HTML PDF 자동 페이지 밀도 조정")
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--chapter", type=int, required=True)
    parser.add_argument("--max-iterations", type=int, default=5)
    parser.add_argument("--min-density", type=float, default=0.75)
    parser.add_argument("--issue-threshold", type=int, default=60,
                        help="페이지 사용률이 이 값(%%) 이하이면 문제로 판정 (기본 60)")
    args = parser.parse_args()

    project_root = args.project_root.resolve()
    override_css = project_root / ".build/_pdf-density.css"
    override_css.parent.mkdir(parents=True, exist_ok=True)

    # density 단계: 1.00, 0.95, 0.90, 0.85, 0.80, 0.75
    steps = [round(1.0 - 0.05 * i, 2) for i in range(args.max_iterations + 1)]
    steps = [s for s in steps if s >= args.min_density]

    best_density: float | None = None
    for i, scale in enumerate(steps):
        print(f"\n━━━ [{i+1}/{len(steps)}] density = {scale:.2f} ━━━")
        # override CSS 갱신 (scale=1.0이면 빈 파일 == 원본 사용)
        override_css.write_text(density_css(scale) if scale < 1.0 else "/* density=1.00 (no override) */", encoding="utf-8")

        pdf_path = rebuild(project_root, args.chapter)
        total_pages, issues = run_layout_check(pdf_path, args.issue_threshold)

        if not issues:
            print(f"\n✅ density={scale:.2f} — 이슈 없음. 종료.")
            best_density = scale
            break

        print(f"⚠️  이슈 {len(issues)}개 (사용률 {args.issue_threshold}%% 미만):")
        for p, u in issues:
            print(f"    p{p:02d}  {u}%")
    else:
        print(f"\n⚠️  density={args.min_density:.2f}까지 축소했지만 이슈 잔존. 수동 판단 필요.")
        best_density = args.min_density

    print(f"\n최종 CSS: {override_css.relative_to(REPO_ROOT)}")
    print(f"최종 PDF: {(project_root / '.build/pdf').relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
