# --------------------------------------
# [기본 애플리케이션 설정]
# --------------------------------------
spring.application.name=spring-oauth-oidc
server.port=8080

# env 파일 읽기
spring.config.import=optional:file:.env[.properties]

# --------------------------------------
# [H2 Database 설정]
# --------------------------------------
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA 설정 (Entity 기반 테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:db/data.sql

# --------------------------------------
# [Kakao OAuth2 설정]
# --------------------------------------
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.authorize-uri=https://kauth.kakao.com/oauth/authorize
kakao.redirect-uri=http://localhost:8080/oauth/callback
kakao.token-uri=https://kauth.kakao.com/oauth/token
kakao.user-info-uri=https://kkakao.com/v2/user/me


# --------------------------------------
# 카카오 OIDC 공개키(JWKS) 조회 주소
# --------------------------------------
# ID Token(JWT)의 서명을 검증하기 위한 공개키 목록(JWKS)을 제공하는 엔드포인트
# 서버는 이 주소에서 공개키를 조회해
# ID Token의 위변조 여부를 검증함
kakao.oidc-jwks-uri=https://kauth.kakao.com/.well-known/jwks.json



