# --------------------------------------
# [기본 애플리케이션 설정]
# --------------------------------------
spring.application.name=spring-presign-url
server.port=8080

# env 파일 읽기
spring.config.import=optional:file:.env[.properties]

# --------------------------------------
# [H2 Database 설정]
# --------------------------------------
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA 설정 (Entity 기반 테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------
# AWS 환경변수 (.env에서 로드)
# ---------------------------
cloud.aws.credentials.access-key=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
cloud.aws.region=${CLOUD_AWS_REGION}
cloud.aws.s3.bucket=${CLOUD_AWS_S3_BUCKET}
