services:
  rabbitmq:
    # RabbitMQ Management 포함 이미지(관리 UI 포함)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq

    # 기본값: 5672(AMQP), 15672(Management UI)
    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      # [필수] 기본 계정(교육/로컬용)
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    # 로컬 실행 기준 재시작 정책
    restart: unless-stopped

    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
